export const nigerianBanks: string[] = [
  "Access Bank",
  "Citibank",
  "Ecobank Nigeria",
  "Fidelity Bank Nigeria",
  "First Bank of Nigeria",
  "First City Monument Bank",
  "Guaranty Trust Bank",
  "Heritage Bank Plc",
  "Jaiz Bank",
  "Keystone Bank Limited",
  "Kuda Bank",
  "Opay",
  "Palmpay",
  "Polaris Bank",
  "Providus Bank Plc",
  "Stanbic IBTC Bank Nigeria Limited",
  "Standard Chartered Bank",
  "Sterling Bank",
  "Suntrust Bank Nigeria Limited",
  "Taj Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa",
  "Unity Bank Plc",
  "Wema Bank",
  "Zenith Bank",
];
